### ISSUE TITLE
Exposing Ircc port for configuration

### ISSUE THREAD

**Issue by PaulWebster** [alexmohr/media_player.sony#18]
The sonyapilib code has provision for the dmr and ircc ports being the same - but for this to be useable it needs the ircc port to be configurable (or some other mechanism to flag it).

I have a KDL-40HX723 and it appears to need this because Ircc.xml not reachable but dmr.xml is and appears to have the required information.

See https://github.com/alexmohr/sonyapilib/issues/51#issuecomment-637486968

**Comment by PaulWebster** [comment]
Sorry - I see that it is configurable in feature branch.

However, when I added it to configuration.xml and restart HA with the branch of media_player installed I get

2020-06-02 13:07:54 ERROR (MainThread) [homeassistant.components.homeassistant] Invalid config for [media_player.sony]: [ircc_port] is an invalid option for [media_player.sony]. Check: media_player.sony->ircc_port. (See ?, line ?).

Perhaps a Python caching issue ... am digging around

**Comment by alexmohr** [comment]
I've merged the pr in the meantime. To make sure HA downloads the correct sonyapi lib version you have download the whole repo again, or at least update the mediaplayer python file and the manifest.json. The last one determines the versions used by HA.

**Comment by alexmohr** [comment]
>
