### ISSUE TITLE
Question: Representation of device in HA

### ISSUE THREAD

**Issue by PaulWebster** [alexmohr/media_player.sony#20]
I have the TV listed as a simple Media Player in HA.
The front page only shows the On/Off button and going into more details gives me the volume controls and FF/REW (video style).
Is there a more complete UI that you can recomment that exposes more remote-like capabilities to HA UI?
I had a look at "TV Remote Card" ( https://github.com/marrobHD/tv-card ) - but have not managed to get it working in Lovelace yet.

**Comment by alexmohr** [comment]
I've always used the UI provided by home assistant. 
Although the plugin you've linked looks great the component just implements a small subset of functions:
* Next track, previous track
* Turn on, off
* Play / Pause / Stop
* Volume control

Other features you'd find on your remote (up, down, numbers ... ) are not implemented in the component.
The media player component would support some additional things ([developer doc](https://developers.home-assistant.io/docs/core/entity/media-player/ )) but not enough to build a full remote. 
Especially the above mentioned buttons are not supported. 
The sony api lib exposes these features and it could be used to implement them in some way. 
If you find a way to integrate these in the component I'd be happy to accept a PR but implementing these is currently not on my agenda.
