### ISSUE TITLE
Send Remote Control Commands

### ISSUE THREAD

**Issue by Jesusgeek316** [alexmohr/media_player.sony#21]
Is it possible to send the commands that are on the remote to the player through Home Assistant? If so, how to you do it?

I'm trying to send arrow keys, select, and eject. At least the eject command seems to be part of sonyapilib, but I don't know enough to try to implement it.

I have a Sony BDP-S3700 registered and connected to Home Assistant.

Thanks.

**Comment by alexmohr** [comment]
At the time this was implemented there was no option to support buttons like this. I'm currently very busy and can't check if this changed but I don't think home assistant offers a way to show these buttons on the UI altough they are implemented in the api lib. 

An option could be to create a button which calls a python script but this would be a bit of programming effort. 
If you have an suggestion on how to implement this or can provide an example for other devices supporting an input like that I'd be more than happy to implement this as soon as my schedule clears up a bit.

**Comment by alexmohr** [comment]
https://github.com/alexmohr/media_player.sony/issues/20 is related to this and aims to improve the UI

**Comment by alexmohr** [comment]
Home assistant still does not support this natively on the UI. 
At the moment the only option you have is described above.
