### ISSUE TITLE
Setup for UBP-x700

### ISSUE THREAD

**Issue by somethingp** [alexmohr/media_player.sony#24]
I can connect fine, but I don't get any information on the play/pause status, or the ability to control it. Is it possible to add this functionality?

**Comment by alexmohr** [comment]
At least Playback control is implemented. A status is not properly published by all devices. 
Are the play pause buttons not visible in home assistant or do they not work properly?

**Comment by somethingp** [comment]
I can see the play pause buttons, but I wanted to automate my lights based on the playing status of the bluray player, and I don't know how to retrieve that status. Is that possible?

**Comment by alexmohr** [comment]
This is not specific for this device. The implementation reports the playback state back to home assistant. Something like media player status. Please look this up in the home assistant documentation.

**Comment by Aohzan** [comment]
@alexmohr I don't have the playback state on my X700, just if the player is `on` or `off`, but no `playing`
according to your answer, it should be report it, right ?

**Comment by alexmohr** [comment]
I think so. could you elaborate what you mean? maybe provide a screenshot or the script you are trying to write

**Comment by Aohzan** [comment]
Sorry for the delay @alexmohr 

So when I play a Blu-Ray :
![2021-07-23-12h50m33](https://user-images.githubusercontent.com/2736322/126772166-7307a73b-fdad-469b-a6dd-ec72f03f0a19.jpg)

Line 236 `self.sonydevice.get_playing_status()` return `NO_MEDIA_PRESENT`

Content returns by the X700
```xml
<?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetTransportInfoResponse xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><CurrentTransportState>NO_MEDIA_PRESENT</CurrentTransportState><CurrentTransportStatus>OK</CurrentTransportStatus><CurrentSpeed>1</CurrentSpeed></u:GetTransportInfoResponse></s:Body></s:Envelope>
```

**Comment by alexmohr** [comment]
This XML is directly provided by the blue ray player therefore it's either not properly implemented or your device does not support this. Can you see this information for example in the Sony TV and sideview app?

**Comment by Aohzan** [comment]
What app are you referring to ?

**Comment by alexmohr** [comment]
https://play.google.com/store/apps/details?id=com.sony.tvsideview.phone&hl=en_US&gl=US

There might be an alternative for iPhones but you'd have to search it yourself.
If the Sony app is able to display the current blue ray let me know. If not it's not supported by your device

**Comment by Aohzan** [comment]
Sadly I don't see any status
![Screenshot_20210727-123009.png](https://user-images.githubusercontent.com/2736322/127139671-22a2f019-dbf7-4c73-af88-316be2f5b969.png)
![Screenshot_20210727-123025.png](https://user-images.githubusercontent.com/2736322/127139682-991e5bda-e4bd-4dd8-b10f-e08a50cdac06.png)

**Comment by alexmohr** [comment]
Probably it's not supported by your device. You could try if it's available via DLNA. But I can't really recommend an app here.

I'm going to close this for now. If it's possible via DLNA feel free to re-open this issue and I'll probably find a way to implement it.

**Comment by Aohzan** [comment]
Thanks :+1:

**Comment by Aohzan** [comment]
I tested with DLNA, the playback status is only available for DLNA pushed content, not disc :(
