### ISSUE TITLE
Platform error media_player.sony - No module named 'sonyapilib'

### ISSUE THREAD

**Issue by rosch100** [alexmohr/media_player.sony#25]
After installing the extension as described, the extension does not start and reports the error:
`Platform error media_player.sony - No module named 'sonyapilib'`
The missing library must obviously installed - but how?

**Comment by alexmohr** [comment]
Please post the used home assistant version the library should be installed automatically

**Comment by alexmohr** [comment]
Also please let me know if the supervised version of home assistant is used

**Comment by rosch100** [comment]
Hi @alexmohr, I'm using Home Assistant 2020.12.1; running on Home Assistant OS 5.9.
(I'm not sure, what a supervised version is?)

**Comment by alexmohr** [comment]
Home assistant os provides the supervised version. Did you install it according to the readme and copied the whole repository?

`put the contents of this repo into /usr/share/hassio/homeassistant/`

**Comment by rosch100** [comment]
I copied the whole repo into custom_components. However, in my home assistant installation, there is currently no directory
`/usr/share/hassio`.
Is it necessary to create the directory `/usr/share/hassio`? This seems not to be right...

**Comment by alexmohr** [comment]
It's been a while since I wrote the documentation probably things have changed by now. I'll take a look into it.

**Comment by rosch100** [comment]
After the installation, a simple "Home assistant restart" did not work. It showed the error message above.
However, a complete reboot of the raspi did the trick. Now it's working.

By the way - changed the installation to HACS, which works as expected.
