### ISSUE TITLE
sonyapilib is still at 0.4.5

### ISSUE THREAD

**Issue by mtdcr** [alexmohr/media_player.sony#27]
Branch master still misses commit 33b9704224f7c0b6e1a1152a19d5e5b9ee688e83, which is available in branch bugfixes.

Would you mind merging this branch in order to enable support for the older Blu-ray models?

For now I was able to just use the bugfixes branch, but this branch doesn't contain commit 79ba6b8ee5332fd5bc1b17bcb69e5cd8eff20676, which sets a version in manifest.json.

**Comment by alexmohr** [comment]
I'll update the master and prepare a new release as soon as possible.

**Comment by alexmohr** [comment]
solved in #29
