### ISSUE TITLE
Version missing from manifest.json

### ISSUE THREAD

**Issue by jasongreb** [alexmohr/media_player.sony#30]
The most recent versions of Home Assistant require that a version be added to the manifest.json file. The add-on wasn't loading. I added this manually with "verison": "0.1.3" and this resolved it. It should be added to the file.

**Comment by alexmohr** [comment]
Manifest.json already contains a version https://github.com/alexmohr/media_player.sony/blob/master/custom_components/sony/manifest.json#L7 ?

**Comment by jasongreb** [comment]
Ah yes, the version I downloaded several months ago did not. I'll check against the version I have and update as necessary.
