### ISSUE TITLE
X1100ES

### ISSUE THREAD

**Issue by rome1983** [alexmohr/media_player.sony#32]
Hi, I got this paired with my sony blu-ray player, but a couple things not working. The on/off states work but not the play/pause states. The on/off button works but the play/pause button acts as the enter button and doesn't pause. I would be happy to get the play/pause states working. Any help would be appreciated. Thanks

**Comment by alexmohr** [comment]
The API library is using a predefined list of key codes if your device does not provide them.
It might be possible that this list ist not matching your device.
To find out which key code is used for play use a packet tracing app, pair your device with the Sony app and start the tracing app. 
Press the keys you need and stop the tracing.
Export the gathered data in pcap format and post it here.

Unfortunately the API documentation is only available for Sony partners

**Comment by rome1983** [comment]
Thanks, any idea on how to get play/pause states reported to home assistant?

**Comment by alexmohr** [comment]
Have you tried what I've suggested in the last comment?
If it worked it would be great to share the key bindings so I can improve the api library.

**Comment by rome1983** [comment]
I don’t have any experience with a packet tracing app. I would need some help. I have a iphone and a Mac mini.

**Comment by rome1983** [comment]
Any help would be appreciated.

**Comment by alexmohr** [comment]
* Setup https://mitmproxy.org/ on you mac
* configure your iPhone to use this as a proxy
* Start the sony app and pair it with your device 
* Press the pause/play button
* Stop the packet caputre in mitmproxy
* Export the data in pcap format 
* Post the pcap file here.

**Comment by alexmohr** [comment]
Another option is to take an sonyapi library example (https://github.com/alexmohr/sonyapilib/blob/master/examples/pair_and_apps.py) and add calls to the buttons you want. Then you'll have to manually match which buttons does which i.e. play is return and return is play. 
Post that matching here and I'll help you with integrating this into home assistant

**Comment by rome1983** [comment]
Thanks, I was able to get paired up with second option. Trying to figure out the rest.

**Comment by alexmohr** [comment]
Do you need further support on this or can this issue be closed?

**Comment by rome1983** [comment]
It can be closed. Thanks
